disabled_rules:
  - force_cast
  - trailing_comma
  - switch_case_alignment
  - opening_brace

opt_in_rules:
  - unneeded_parentheses_in_closure_argument

line_length:
  warning: 120

function_body_length:
  warning: 50

excluded:
  - Tests/ReflowTests/XCTestManifests.swift
