#if !canImport(ObjectiveC)
import XCTest

extension CombineReducersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CombineReducersTests = [
        ("testCombineReducers", testCombineReducers),
        ("testWithKey", testWithKey),
    ]
}

extension DispatchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DispatchTests = [
        ("testDispatchAction", testDispatchAction),
        ("testDispatchAsyncEffect", testDispatchAsyncEffect),
        ("testDispatchSyncEffect", testDispatchSyncEffect),
        ("testEffectCanAccessState", testEffectCanAccessState),
        ("testEffectDispatch", testEffectDispatch),
    ]
}

extension MiddlewareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MiddlewareTests = [
        ("testMiddlewareCanAccessState", testMiddlewareCanAccessState),
        ("testMiddlewareDispatch", testMiddlewareDispatch),
        ("testMiddlewareDispatcher", testMiddlewareDispatcher),
    ]
}

extension StoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StoreTests = [
        ("testStoreInit", testStoreInit),
        ("testStoreSelect", testStoreSelect),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CombineReducersTests.__allTests__CombineReducersTests),
        testCase(DispatchTests.__allTests__DispatchTests),
        testCase(MiddlewareTests.__allTests__MiddlewareTests),
        testCase(StoreTests.__allTests__StoreTests),
    ]
}
#endif
